server:
  port: 10933

spring:
  datasource:
    url: jdbc:mysql://storm01:3306/grafana?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#  thymeleaf:
#    mode: HTML5
#    encoding: UTF-8
#    content-type: text/html
#    cache: true

influxdb:
  url: http://storm01:8086
  user: root
  password: root

grafana:
  url: http://storm01:3000
  api.key: eyJrIjoic1FJaFliTTNwUEo1QTR4OFFINDJwWjZQaEdBUnBaNkoiLCJuIjoiYWRtaW4iLCJpZCI6MX0=

kapacitor:
  url: http://storm01:9093

storm:
  cluster:
    url: http://storm01:18080
  database: application
  measurement: storm

zookeeper:
  cluster:
    url: storm01:2181,storm02:2181,storm03:2181
  database: application
  measurement: zookeeper

