server:
  port: 10933

spring:
  datasource:
    url: jdbc:mysql://192.168.99.169:3306/grafana?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: MyNewPass4!
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

influxdb:
  url: http://192.168.99.225:8086
  user: root
  password: root