server:
  port: 10933

spring:
  datasource:
    url: jdbc:mysql://home-nuc:3306/grafana?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin@123_KOFEE
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#  thymeleaf:
#    mode: HTML5
#    encoding: UTF-8
#    content-type: text/html
#    cache: true

influxdb:
  url: http://home-nuc:8086
  user: root
  password: root

grafana:
  url: http://home-nuc:3000
  api.key: eyJrIjoieHdMU0V4MTc3Z09FbFJRbmdXVmJGMWhKSmhFNnczSkUiLCJuIjoiYWRtaW4iLCJpZCI6MX0=

kapacitor:
  url: http://home-nuc:9093


